update phpx

diff --git a/PHP/phpx b/PHP/phpx
--- a/PHP/phpx
+++ b/PHP/phpx
@@ -38,35 +38,34 @@ validate_php_version() {
 }
 
 add_sury_repo_if_needed() {
-    if [ -f /etc/os-release ]; then
-        . /etc/os-release
-        OS=$ID
-    else
-        echo "Cannot determine the operating system."
-        exit 1
-    fi
+  if [ -f /etc/os-release ]; then
+    . /etc/os-release
+    OS=$ID
+  else
+    echo -e "${RED}Cannot determine the operating system.${NC}"
+    exit 1
+  fi
 
-    if [ "$OS" == "ubuntu" ]; then
-        if ! grep -q "^deb .*ondrej/php" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
-            echo "Adding the Sury PPA for Ubuntu."
-            sudo apt update
-            sudo apt install -y software-properties-common
-            sudo add-apt-repository ppa:ondrej/php
-            sudo apt update
-        fi
-    elif [ "$OS" == "debian" ] || [ -n "$(grep -i 'debian' /etc/os-release)" ]; then
-        if ! grep -q "^deb .*packages.sury.org/php" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
-            echo "Adding the Sury repository for Debian."
-            sudo apt update
-            sudo apt install -y apt-transport-https lsb-release ca-certificates curl
-            curl -fsSL https://packages.sury.org/php/apt.gpg | sudo tee /etc/apt/trusted.gpg.d/sury-php.gpg > /dev/null
-            echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/sury-php.list
-            sudo apt update
-        fi
-    else
-        echo "Unsupported OS for this script."
-        exit 1
+  if [ "$OS" == "ubuntu" ]; then
+    if ! grep -q "^deb .*ondrej/php" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
+      echo -e "${YELLOW}Adding the Sury PPA for Ubuntu.${NC}"
+      add-apt-repository ppa:ondrej/php
+      apt update
     fi
+  elif [ "$OS" == "debian" ] || [ -n "$(grep -i 'debian' /etc/os-release)" ]; then
+    if ! grep -q "^deb .*packages.sury.org/php" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
+      echo -e "${YELLOW}Adding the Sury PPA for Debian.${NC}"
+      apt update
+      apt -y install lsb-release ca-certificates curl
+      curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
+      dpkg -i /tmp/debsuryorg-archive-keyring.deb
+      sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
+      apt update
+    fi
+  else
+    echo -e "${RED}Unsupported OS for this script.${NC}"
+    exit 1
+  fi
 }
 
 install_php_version() {
